### ISSUE TITLE
Inability to unpack dnstap message to a Msg structure

### ISSUE THREAD

**Issue by edevil** [dnstap/golang-dnstap#44]
I've noticed that some dnstap responses from unbound are unable to be parsed. `dig` also complains in this case, so I'm unsure if the problem is in the DNS response itself, Unbound handling it, or this dnstap library.

This is the query/response:
```
❯ dig +short AAAA vstbrasil.com.
;; Warning: Message parser reports malformed message packet.
```

This is the output of dnstap:
```
16:45:28.364170 CQ 127.0.0.1 UDP 42b "vstbrasil.com." IN AAAA
16:45:28.968713 CR 127.0.0.1 UDP 58b X
```

The error occurs on msg.Unpack: `"overflow unpacking aaaa"`

**Comment by pmazzini** [comment]
@edevil We recently started seeing this issue on some hosts after upgrading unbound from 1.9.6 to 1.16.1.

Is the issue still happening for you? Can you still reproduce it with the above `dig` command?

**Comment by edevil** [comment]
As far as I know it still happens, although it's been a while since I looked at it. https://github.com/NLnetLabs/unbound/issues/653

**Comment by cmikk** [comment]
The `msg.Unpack` code is in `github.com/miek/dns`, and appears to be failing due to a malformed AAAA RR in the response. The `dnstap` utility's YAML and JSON formats do include the error message, but the quiet text format omits it in the name of simplicity.

In short, everything appears to be working as intended here, other than (presumably) the authoritative name server returning an invalid AAAA record, and I would suggest using the YAML or JSON output formats if you want more verbose error reporting than `X`.
